services:
  db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aqua909020
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: inventory-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: aqua909020
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./target:/app/target
      - ~/.m2:/root/.m2
    restart: unless-stopped

volumes:
  postgres_data: